// Code generated by mockery v2.53.5. DO NOT EDIT.

package router_mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Router is an autogenerated mock type for the Router type
type Router struct {
	mock.Mock
}

// Handle provides a mock function with given fields: method, pattern, handler
func (_m *Router) Handle(method string, pattern string, handler http.Handler) {
	_m.Called(method, pattern, handler)
}

// ServeHTTP provides a mock function with given fields: _a0, _a1
func (_m *Router) ServeHTTP(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// Use provides a mock function with given fields: middlewares
func (_m *Router) Use(middlewares ...func(http.Handler) http.Handler) {
	_va := make([]interface{}, len(middlewares))
	for _i := range middlewares {
		_va[_i] = middlewares[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// NewRouter creates a new instance of Router. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Router {
	mock := &Router{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
